export enum EVENT_TYPE {
  FROM_PAGE = "FROM_PAGE",
  FROM_EXTENSION = "FROM_EXTENSION",
  FROM_BG = "FROM_BG",
  FROM_CONTENT = "FROM_CONTENT"
}

export enum EVENT_ACTION {
  EXT_LOST_CONNECTION = "EXT_LOST_CONNECTION",
  EXT_CHECK = "EXT_CHECK",
  EXT_PRESENT = "EXT_PRESENT",
  SEND_PROMPT = "SEND_PROMPT",
  GET_PROOF_TOKEN = "GET_PROOF_TOKEN",
  GET_BROWSER_INFO = "GET_BROWSER_INFO",
  SSE_PART = "SSE_PART",
  SSE_DONE = "SSE_DONE",
  GPT_STREAM_PART = "GPT_STREAM_PART",
  GPT_STREAM_DONE = "GPT_STREAM_DONE"
}